# Generated by Django 4.1.7 on 2023-04-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=40)),
                ('password', models.TextField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
