# Generated by Django 4.1.7 on 2023-04-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_vehicle', '0002_signup2_delete_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup2',
            new_name='signup',
        ),
    ]
