# Generated by Django 4.1.7 on 2023-04-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_vehicle', '0004_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('vno', models.TextField(max_length=30)),
                ('yop', models.IntegerField(max_length=4)),
                ('repaird', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='vehicles',
        ),
    ]
