# Generated by Django 4.1.7 on 2023-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_vehicle', '0007_vehicles_engine_oil_alter_vehicles_repaird_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('vno', models.TextField(max_length=30)),
                ('yop', models.IntegerField()),
                ('engine_oil', models.TextField()),
                ('repaird', models.IntegerField()),
                ('brake', models.TextField()),
                ('tyre', models.TextField()),
                ('physical', models.TextField(default='NAN')),
            ],
        ),
        migrations.DeleteModel(
            name='vehicles',
        ),
    ]
